#!/usr/bin/env bash

MY_SCRIPT=`basename "$0"`

if [ "$#" -eq "1" ] 
then
    PROCESS=`ps aux | grep -i $1 | grep -v $MY_SCRIPT | grep -v "grep" | awk -F' ' '{ print $2 }'`;
    for a in $PROCESS; do {
      kill -9 $a;
    }; done;
else 
    echo "usage: killallprocess PATTERN"
fi

exit $?
